# Travis CI integration -- https://travis-ci.org/troglobit/libuev
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We don't need to install packages, use dockerized build, quicker
sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ikQcWMCLFoxq0+wMiqrNT5HRn0d4e3AxuF8VzNUNFrk6jUvHIufC/OKvr8VWPTjCaAQXZjWfdQAAARUXzJV10WZ7xpiv5qt4bt26Qih2AwMPMJeUOYrqXgQqhTPBp05iLYpo4ybICteXRI3zKKUA1wkdDC0jyu3rl+Fbveekbe0="

addons:
  coverity_scan:
    project:
      name: "troglobit/libuev"
      description: "libuEv | Simple event loop for Linux"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen && ./configure --enable-examples"
    build_command: "make clean all"
    branch_pattern: dev

# We don't use configure, so we must define our own build script.
script:
  - ./autogen.sh
  - ./configure --disable-silent-rules --enable-examples
  - make -j5 clean all
  - make test
